version: '3'
services:
    mariadb:
        restart: unless-stopped
        build:
            context: './mariadb'
            dockerfile: 'Dockerfile'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'scuffedware'
            MYSQL_USER: 'sysadmin'
            MYSQL_PASSWORD: 'Victorerenkvinde123'
        volumes:
            - 'mariadb:/var/lib/mysql'
        networks:
            - network
    nginx:
        restart: unless-stopped
        image: 'nginx:1.23'
        ports:
            - '80:80'
            - '443:443'
        networks:
            - network
        volumes:
            - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    node:
        restart: unless-stopped
        build:
            context: './node'
            dockerfile: 'Dockerfile-dev'
        networks:
            - network
        volumes:
            - './node:/usr/src/app'
    frontend:
        restart: unless-stopped
        build:
            context: './frontend'
            dockerfile: 'Dockerfile-dev'
        networks:
            - network
        volumes:
            - './frontend:/usr/src/app'
        environment: 
             - CHOKIDAR_USEPOLLING=true
networks:
    network:
        driver: bridge
volumes:
    mariadb:
        driver: local
